SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

BALL_SIZE = 30
BALL_KILL_THRESH = BALL_SIZE // 2    # when do we kill the ball if it flies past the paddle

PADDLE_INITIAL_HEIGHT = 300
PADDLE_WIDTH = 30

HIT_ACCELERATION = 1.1

DEBUG = True